export { AuthTitle } from './ui/auth-title/auth-title'
export { instance } from './api/api.instance'
export type { ISignUp, ISignIn } from './model/interfaces/auth.interfaces'
export { authService } from './api/services/auth.service'
export { QUERY_KEYS } from './model/constants'
export { usePostSignUp, usePostSignIn } from './api/queries/auth.queries'
